In [2]:
from models.cvm import CVM
import numpy as np

c:\Users\Wen Kang\Desktop\final_year_project\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
cvm = CVM("20230307_211536.txt")

In [3]:
data = np.loadtxt("output\\20230307_211536.txt", delimiter=',')

In [4]:
data.shape

(6079, 10)

In [5]:
data

array([[ 1.00000e+00,  1.30000e+01,  1.86800e+03, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00],
       [ 1.00000e+00,  1.20000e+01,  8.48000e+02, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00],
       [ 1.00000e+00,  1.10000e+01,  9.21000e+02, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00],
       ...,
       [ 6.00000e+02,  2.72000e+02,  5.89990e+02, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00],
       [ 6.00000e+02,  2.62000e+02,  1.25805e+03, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00],
       [ 6.00000e+02,  2.07000e+02,  1.02520e+03, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00]])

In [6]:
ext = np.where((data[:, 1] == 1) & (data[:, 0] <= 30) & (data[:, 0] >= np.max(30 - 15, 0)))

In [7]:
proc_data = data[ext]

In [8]:
proc_data.shape

(16, 10)

In [9]:
bbox_data = proc_data[:, 2:6]
bbox_vel = np.diff(bbox_data, n=1, axis=0)
mean_vel = bbox_vel.mean(axis=0)

In [10]:
mean_vel

array([ 8.67133333, -1.032     ,  1.698     ,  2.51      ])

In [11]:
sigma = np.diag(np.full(4,1))

In [12]:
future_steps = np.random.default_rng().multivariate_normal(mean_vel, sigma, (40, ))

In [13]:
future_steps.shape

(40, 4)

In [14]:
future_vel = np.cumsum(future_steps, axis=0)

In [15]:
future_positions = proc_data[-1, 2:6] + future_vel

In [16]:
future_positions

array([[1584.6026068 ,  392.10115199,  153.84555245,  434.21685302],
       [1592.29337974,  391.24130109,  154.94648326,  437.01191088],
       [1600.42265947,  390.75973304,  157.76800335,  438.82708408],
       [1610.22171884,  391.23518927,  158.22346337,  441.84461777],
       [1618.15835344,  390.12023383,  158.81479731,  444.53563913],
       [1626.18637142,  389.09815   ,  161.13419924,  447.80577671],
       [1635.84659138,  388.92646123,  163.33146892,  448.75900369],
       [1644.50960943,  387.80160139,  163.51146656,  451.211793  ],
       [1653.25806753,  386.79729575,  164.55826936,  455.21950448],
       [1659.91307592,  386.38659871,  166.90785822,  458.92879223],
       [1669.81416444,  385.39754227,  167.96218276,  463.17386211],
       [1678.09250304,  383.92657867,  167.93183953,  465.64909069],
       [1687.88924187,  383.35442633,  169.01863847,  468.40505467],
       [1695.67133826,  379.70530931,  172.25430013,  472.16344493],
       [1705.37989245,  379.205295

In [26]:
p_id = np.full((40, 1), 1)
padding = np.full((40, 1), 1)

frame_id = 30 + np.arange(1, 40 + 1).reshape(-1, 1)

In [37]:
def format_MOT_output(vel, frame_id, p_id, future_positions):
    return

np.pad(np.hstack((frame_id, p_id, future_positions, )),  ((0, 0), (0, 3)), 'constant', constant_values=-1)

array([[ 3.10000000e+01,  1.00000000e+00,  1.58460261e+03,
         3.92101152e+02,  1.53845552e+02,  4.34216853e+02,
        -1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 3.20000000e+01,  1.00000000e+00,  1.59229338e+03,
         3.91241301e+02,  1.54946483e+02,  4.37011911e+02,
        -1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 3.30000000e+01,  1.00000000e+00,  1.60042266e+03,
         3.90759733e+02,  1.57768003e+02,  4.38827084e+02,
        -1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 3.40000000e+01,  1.00000000e+00,  1.61022172e+03,
         3.91235189e+02,  1.58223463e+02,  4.41844618e+02,
        -1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 3.50000000e+01,  1.00000000e+00,  1.61815835e+03,
         3.90120234e+02,  1.58814797e+02,  4.44535639e+02,
        -1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 3.60000000e+01,  1.00000000e+00,  1.62618637e+03,
         3.89098150e+02,  1.61134199e+02,  4.478057